add folder jsBasics with files home work #3
ShostVladyslav/aqa-advanced pull request #3
Opened 2024-01-24 19:44 UTC by ShostVladyslav

2024-01-24 21:06 UTC, sttaran requested changes

2024-01-24 21:06 UTC, sttaran commented on jsBasics/task1.js
> +const email =
when you use const you should assign value immediately

2024-01-24 21:06 UTC, sttaran commented on jsBasics/task1.js
> +const email =
but you can use `let`

2024-01-24 21:06 UTC, sttaran commented on jsBasics/task3.js
> +let isAdult = ageSemen >= 18
use const

2024-01-25 11:23 UTC, sttaran requested changes

2024-01-25 11:23 UTC, sttaran commented on jsBasics/task1.js
> +let email =
remove =

2024-01-25 11:39 UTC, ShostVladyslav commented on jsBasics/task1.js
> +let email =
done

2024-01-28 20:56 UTC, sttaran approved these changes

2024-01-29 09:01 UTC, merged